<a href="https://colab.research.google.com/github/100455376/100455376/blob/main/Extra_Assignment_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Extra Assignment: QR Factorization and Eigenvalue Computation

## Objective
In this assignment, you will explore different approaches to QR factorization and apply them to compute eigenvalues using the unshifted QR algorithm. The goal is to analyze the performance, accuracy, and numerical stability of different methods.

## Learning Outcomes
By completing this assignment, you will:
- Implement QR factorization using **Givens rotations**.
- Compare it with **Householder reflections** (which was covered in class).
- Utilize **NumPy's built-in QR factorization** for reference.
- Apply the **unshifted QR algorithm** to compute eigenvalues.
- Analyze the performance and accuracy of these methods.

## Background
QR factorization decomposes a matrix $A$ into an orthogonal matrix $Q$ and an upper triangular matrix $R$:
$$
A = QR
$$
This decomposition is fundamental in solving least squares problems and in computing eigenvalues using iterative methods such as the **QR algorithm**.

The **unshifted QR algorithm** consists of iteratively factorizing a matrix into $QR$, then updating it as:
$$
A_{k+1} = R_k Q_k
$$
This process typically converges to an upper triangular matrix whose diagonal entries approximate the eigenvalues of $A$.


## Why Compare Different Methods?

- **Givens rotations** are numerically stable and efficient for sparse matrices.
- **Householder reflections** are widely used due to their efficiency in dense matrices.
- **NumPy's built-in QR** is optimized and serves as a benchmark.
- Comparing these approaches helps in understanding their trade-offs.


---

## **Givens Rotations: An Overview**  

Givens rotations are a technique used in numerical linear algebra to introduce zeros into matrices. They are particularly useful for QR factorization and solving least squares problems. Unlike Householder reflections, which operate on entire columns, Givens rotations only affect two rows at a time, making them efficient for sparse matrices.

#### Definition of a Givens Rotation
A **Givens rotation** is a special orthogonal transformation represented by a rotation matrix $G(i, j, \theta)$ that operates on two coordinates (rows) of a matrix:

$$
G(i, j, \theta) =
\begin{bmatrix}
1 &  &  &  &  \\
& \ddots &  &  &  \\
&  & c & s &  \\
&  & -s & c &  \\
&  &  &  & \ddots \\
\end{bmatrix}
$$

where $c = \cos(\theta)$ and $s = \sin(\theta)$. The rotation only affects rows $i$ and $j$ of the matrix.


#### Zeroing Out a Matrix Entry
Given a matrix $A$, we want to introduce a zero in position $A_{j,k}$ while preserving the norm of the affected elements. The Givens rotation achieves this by choosing:
$$
c = \frac{a}{\sqrt{a^2 + b^2}}, \quad s = \frac{b}{\sqrt{a^2 + b^2}}
$$
where $a = A_{i,k}$ and $b = A_{j,k}$.

Applying $G(i, j, \theta)$ on the left of $A$ updates only the rows $i$ and $j$ as follows:
$$
\begin{bmatrix} c & s \\ -s & c \end{bmatrix} \begin{bmatrix} a \\ b \end{bmatrix} = \begin{bmatrix} \sqrt{a^2 + b^2} \\ 0 \end{bmatrix}
$$

This ensures that the entry $A_{j,k}$ is zeroed out.


#### *Example done in class*

Find a Givens rotation $G$ with the property that $GA$ has a zero entry in the second row and first column, where  

$$
A =
\begin{bmatrix}
3 & 1 & 0 \\
1 & 3 & 1 \\
0 & 1 & 3
\end{bmatrix}.
$$

*Solution:* The form of $G$ is  

$$
G =
\begin{bmatrix}
\cos\theta & \sin\theta & 0 \\
-\sin\theta & \cos\theta & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

so  

$$
GA =
\begin{bmatrix}
3\cos\theta + \sin\theta & \cos\theta + 3\sin\theta & \sin\theta \\
-3\sin\theta + \cos\theta & -\sin\theta + 3\cos\theta & \cos\theta \\
0 & 1 & 3
\end{bmatrix}.
$$

The angle $\theta$ is chosen so that $-3\sin\theta + \cos\theta = 0$, that is, so that $\tan\theta = \frac{1}{3}$. Hence  

$$
\cos\theta = \frac{3\sqrt{10}}{10}, \quad \sin\theta = \frac{\sqrt{10}}{10}.
$$

and  

$$
GA =
\begin{bmatrix}
\frac{3\sqrt{10}}{10} & \frac{\sqrt{10}}{10} & 0 \\
-\frac{\sqrt{10}}{10} & \frac{3\sqrt{10}}{10} & 0 \\
0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
3 & 1 & 0 \\
1 & 3 & 1 \\
0 & 1 & 3
\end{bmatrix}
=
\begin{bmatrix}
\sqrt{10} & \frac{3}{5}\sqrt{10} & \frac{1}{10}\sqrt{10} \\
0 & \frac{4}{5}\sqrt{10} & \frac{3}{10}\sqrt{10} \\
0 & 1 & 3
\end{bmatrix}.
$$

Note that the resulting matrix is neither symmetric nor tridiagonal.

#### QR Factorization Using Givens Rotations

To compute the QR decomposition using Givens rotations:
1. Start with $A$ and initialize $Q$ as an identity matrix.
2. For each subdiagonal element $A_{j,k}$ (where $j > k$), apply a Givens rotation to zero it out.
3. Multiply $Q$ by each rotation matrix $G(i, j, \theta)$ in sequence.
4. The final $Q$ is the product of all Givens rotations, and $R$ is the transformed upper triangular matrix.

#### Advantages and Disadvantages

**Advantages:**
- Efficient for **sparse** matrices since it only modifies two rows at a time.
- **Numerically stable** since it relies on orthogonal transformations.
- Parallelizable for certain architectures.

**Disadvantages:**
- Computationally more expensive than Householder reflections for dense matrices (since each element must be zeroed out individually).
- More complex to implement than the standard Gram-Schmidt process.

#### Application to Eigenvalue Computation

Givens rotations can be used in the **unshifted QR algorithm**, where repeated QR factorizations are applied to approximate the eigenvalues of a matrix. Since Givens rotations maintain numerical stability, they are effective for iterative QR methods.




---

## Tasks
### **Task 1: QR Factorization using Givens Rotations**
1. Implement QR factorization using **Givens rotations**.
2. Test your implementation on a sample matrix and verify the results.

### **Task 2: QR Factorization using Householder Reflections**
1. Implement QR factorization using **Householder reflections** (or reuse your class implementation).
2. Compare its performance and results with the Givens rotations method.

### **Task 3: QR Factorization using NumPy**
1. Use `numpy.linalg.qr` to compute the QR decomposition.
2. Compare its results with your previous implementations.

### **Task 4: Eigenvalues via the Unshifted QR Algorithm**
1. Implement the **unshifted QR method** for eigenvalue computation.
2. Apply it using:
   - Givens rotations
   - Householder reflections
   - NumPy's QR factorization
3. Analyze the convergence behavior and accuracy.

### **Task 5: Performance Comparison and Discussion**
1. Compare the computational efficiency of the three QR methods.
2. Discuss numerical stability and accuracy.
3. Provide plots (if necessary) to illustrate convergence differences.
4. Conclude which method is preferable in different scenarios.

---

## Implementation Details
- Use Python and NumPy for implementation.
- Ensure code is well-commented and modular.
- Test with different matrices (e.g., random, symmetric, and non-symmetric matrices).
- Use relative errors to compare accuracy.
- Measure execution time for performance analysis.

---


In [3]:
# 1. Implement QR factorization using **Givens rotations**.
# 2. Test your implementation on a sample matrix and verify the results.

# QR factorization zeroes out one subdiagonal element A_i,j using Givens rotation G(i,j,theta) using c, s formulas with A_i,i=a and A_j,i=b
# A<-G*A and then accumulate rotations into Q<-Q*G^T
import numpy as np # Libraries

def givens_rotation(a, b): # Givens rotation that zeroes out b given a, b
    if b == 0:
        return 1.0, 0.0
    else:
        r = np.hypot(a, b)  # formula sqrt(a^2 + b^2), stable
        c = a / r
        s = b / r  # (note the sign choice is up to convention)
        return c, s # Return c and s

def qr_givens(A): # Givens QR factorization of A

    A = A.copy().astype(float)
    m, n = A.shape
    Q = np.eye(m)

    for j in range(n): # for each column
        for i in range(j+1, m): # and each row below diagonal
            # Want to zero out A[i, j] using a Givens rotation
            a = A[j, j]
            b = A[i, j]
            if abs(b) < 1e-12:
                continue  # Already effectively zero
            c, s = givens_rotation(a, b) # Compute Givens rotation

            # Givens matrix G for rows j and i
            G = np.eye(m)
            G[j, j] = c
            G[j, i] = -s
            G[i, j] = s
            G[i, i] = c

            # Update A
            A = G @ A
            # Update Q
            Q = Q @ G.T  # Alternatively: G^T @ Q, depending on convention

    R = A # In theend, R=A
    return Q, R # Fnally, return matrices Q and R


# Test & debug
A_test = np.array([[3.0, 1.0, 0.0],
                   [1.0, 3.0, 1.0],
                   [0.0, 1.0, 3.0]])

Q_g, R_g = qr_givens(A_test) # Q should be orthogonal (Q*Q^T=I) and Q*R≅A
print("Q_g:\n", Q_g)
print("R_g:\n", R_g)
print("A_test:\n", A_test)
print("Check Q_g * R_g:\n", Q_g @ R_g)  # should be close to A_test and indeed it is :)


Q_g:
 [[ 0.9486833   0.30151134  0.09534626]
 [-0.31622777  0.90453403  0.28603878]
 [ 0.         -0.30151134  0.95346259]]
R_g:
 [[ 2.52982213e+00 -5.55111512e-17 -3.16227766e-01]
 [ 1.80906807e+00  2.71360210e+00 -1.11022302e-16]
 [ 5.72077554e-01  1.90692518e+00  3.14642654e+00]]
A_test:
 [[3. 1. 0.]
 [1. 3. 1.]
 [0. 1. 3.]]
Check Q_g * R_g:
 [[ 3.00000000e+00  1.00000000e+00 -4.27777916e-17]
 [ 1.00000000e+00  3.00000000e+00  1.00000000e+00]
 [-4.56775103e-17  1.00000000e+00  3.00000000e+00]]


 **TASK 1: **
  Once we tested the implementation we can quickly verify that the result is the intended one and values are very very close so developed method works.

In [5]:
def qr_householder(A): # QR factorization via Householder method
  # by forming HOuseholder matrix H_k and applying it to A from left to update it and accumulate transformations in Q use v and H formulas as in classs
    A = A.copy().astype(float)
    m, n = A.shape
    Q = np.eye(m)

    for k in range(n): # Iterate through each column k
        x = A[k:, k] # Extracting the vector we want to zero below the diagonal
        if np.allclose(x[1:], 0):
            continue # nothing to zero out


        norm_x = np.linalg.norm(x) # Compute the norm # and create reflection vector:
        sign = -1 if x[0] < 0 else 1
        u1 = x[0] - sign * norm_x
        v = x.copy()
        v[0] = u1
        beta = v @ v

        if abs(beta) < 1e-12:
            continue # skip if v is nearly zero

        A[k:, k:] -= (2.0 / beta) * np.outer(v, np.dot(v, A[k:, k:])) # Update the submatrix of A by formula: A[k:, k:]=A[k:, k:]-(2/β)*v*(vᵀ A[k:, k:])
        Q[:, k:] -= (2.0 / beta) * np.outer(np.dot(Q[:, k:], v), v) # Update Q with formula Q[:, k:]=Q[:, k:]-(2/β)*(Q[:, k:]v)vᵀ

    R = A # Lately R is A
    return Q, R # Return matrices

# Test and debuging
A_test = np.random.rand(5, 3)
Q_h, R_h = qr_householder(A_test)
print("Q_h:\n", Q_h)
print("R_h:\n", R_h)
print("Q orthogonality:\n", Q_h.T*Q_h)
print("Q_h * R_h:\n", Q_h @ R_h)# Should approximate A_test
print("Original A_test:\n", A_test)

Q_h:
 [[ 0.02612023  0.60033678 -0.00868161  0.78045793 -0.17240515]
 [ 0.57740046 -0.25540552  0.25250477  0.3251226   0.65720116]
 [ 0.42660688 -0.23562057  0.54111197  0.0216664  -0.68499483]
 [ 0.43533572  0.70678586  0.12322017 -0.53290119  0.1084881 ]
 [ 0.54260097 -0.13892611 -0.79257845  0.02697417 -0.23953187]]
R_h:
 [[ 1.42873749e+00  7.29385685e-01  8.35651383e-01]
 [ 0.00000000e+00  8.76655320e-01  2.85475099e-01]
 [ 0.00000000e+00 -6.93889390e-18  2.27212129e-01]
 [ 0.00000000e+00 -2.22044605e-16 -4.16333634e-17]
 [ 0.00000000e+00 -2.77555756e-17  8.32667268e-17]]
Q orthogonality:
 [[ 0.00068227  0.34663474 -0.00370363  0.33976122 -0.0935472 ]
 [ 0.34663474  0.06523198 -0.05949532  0.22979206 -0.0913024 ]
 [-0.00370363 -0.05949532  0.29280216  0.00266974  0.54291214]
 [ 0.33976122  0.22979206  0.00266974  0.28398368  0.00292638]
 [-0.0935472  -0.0913024   0.54291214  0.00292638  0.05737552]]
Q_h * R_h:
 [[0.03731895 0.54534015 0.19123604]
 [0.82495369 0.19724502 0.46696572

**TASK 2:**
 Again we can see that objective is achieved QR matches excatly A (original matrix), Q is close to being orthogonal although has a bigger error than I expected. Goal was that this method should work better than previous (task 1) but we get the same results when run together for same matrix. And that means that both methods have been correctly implemented since methods are equivalent:

In [6]:
# All 2 together for comparison:
print("A_test:\n", A_test)
Q_g, R_g = qr_givens(A_test)
print("Check Q_g * R_g:\n", Q_g @ R_g)
Q_h, R_h = qr_householder(A_test)
print("Q_h * R_h:\n", Q_h @ R_h)

A_test:
 [[0.03731895 0.54534015 0.19123604]
 [0.82495369 0.19724502 0.46696572]
 [0.60950925 0.10460293 0.41217803]
 [0.62198047 0.93713523 0.59355578]
 [0.77523435 0.27397507 0.23368187]]
Check Q_g * R_g:
 [[0.03731895 0.54534015 0.19123604]
 [0.82495369 0.19724502 0.46696572]
 [0.60950925 0.10460293 0.41217803]
 [0.62198047 0.93713523 0.59355578]
 [0.77523435 0.27397507 0.23368187]]
Q_h * R_h:
 [[0.03731895 0.54534015 0.19123604]
 [0.82495369 0.19724502 0.46696572]
 [0.60950925 0.10460293 0.41217803]
 [0.62198047 0.93713523 0.59355578]
 [0.77523435 0.27397507 0.23368187]]


In [7]:
# Now run it using numpy
A_test = np.random.rand(5, 5) # for some rand.matrix
Q_np, R_np = np.linalg.qr(A_test)

Q_g, R_g = qr_givens(A_test) # Compare to Givens's decomposition
Q_h, R_h = qr_householder(A_test) # Compare to Householder's decomposition

# Check differences
print("||Q_np @ R_np - A_test|| = ", np.linalg.norm(Q_np @ R_np - A_test))
print("||Q_g  @ R_g  - A_test|| = ", np.linalg.norm(Q_g  @ R_g  - A_test))
print("||Q_h  @ R_h  - A_test|| = ", np.linalg.norm(Q_h  @ R_h  - A_test))

||Q_np @ R_np - A_test|| =  6.668945806296229e-16
||Q_g  @ R_g  - A_test|| =  5.604016067269809e-16
||Q_h  @ R_h  - A_test|| =  5.954954746056748e-16


**TASK 3:**
 For comparison purposes use the errors, results are very small as the exponents in the roder of 16 show, so clearly the methods are all working and in a similar way in terms of accuracy level for the decomposition of the matrix.

In [13]:
import numpy as np

# Remember and note about unshifted QR method:
# A_k+1=R_k*Q_k where A_k=R_k*Q_k QR factorization
# Repeat until: i) Convergence (A_k becomes almost upper-triangular)
#             ii) Changes get very small
# Diagonal of final matrix has eigenvalues that we need to extract
# 3 factorizations to be used:
#   (Q_k, R_k) = qr_givens(A_k)
#   (Q_k, R_k) = qr_householder(A_k)
#   (Q_k, R_k) = np.linalg.qr(A_k)
# Common approach is to check the size of the subdiagonal elements.
# When small enough (below some tolerance) -> assume convergence.

def unshifted_qr_eig(A, method='givens', max_iter=1000, tol=1e-12):  # Compute eigenvalues via unshifted QR iteration
    A_k = A.copy().astype(float)
    n = A_k.shape[0]
    off_diag_history = []  # To record the off-diagonal norm over iterations

    for iteration in range(max_iter):  # First, factorize A_k
        if method == 'givens':
            Q_k, R_k = qr_givens(A_k)
        elif method == 'householder':
            Q_k, R_k = qr_householder(A_k)
        else:
            Q_k, R_k = np.linalg.qr(A_k)

        A_next = R_k @ Q_k  # Second, update A_{k+1}
        off_diag_norm = np.linalg.norm(np.tril(A_next, -1))  # Check convergence by looking at the norm of subdiagonal part
        off_diag_history.append(off_diag_norm)  # Store this norm for analysis
        A_k = A_next  # Iterate
        if off_diag_norm < tol:  # Check tolerance level
            break

    # Eigenvalues on the diagonal
    return np.diag(A_k), A_k, iteration + 1, off_diag_history  # returning final matrix, iteration count & history

# --- Example implementations for qr_givens and qr_householder ---
# Replace these with your actual implementations if available.
def qr_givens(A):
    # Placeholder: using NumPy's QR (replace with your Givens rotations-based QR)
    return np.linalg.qr(A)

def qr_householder(A):
    # Placeholder: using NumPy's QR (replace with your Householder reflections-based QR)
    return np.linalg.qr(A)

# Test in an easy matrix
A_test = np.array([[4, 1, 0],
                   [1, 4, 1],
                   [0, 1, 4]], dtype=float)

eigs, A_final, iter_count, off_hist = unshifted_qr_eig(A_test, method='givens') # Givens
print("Eigenvalues (unshifted QR with Givens):", eigs) # Print eigenvalues for Givens
print("Iterations (Givens):", iter_count) # Print number of iterations for G

eigs, A_final, iter_count, off_hist = unshifted_qr_eig(A_test, method='householder') # Householder
print("Eigenvalues (unshifted QR with Householder):", eigs)# Print eigenvalues for Householder
print("Iterations (Householder):", iter_count) # Print number of iterations for HH

eigs, A_final, iter_count, off_hist = unshifted_qr_eig(A_test, method='numpy') # Numpy
print("Eigenvalues (unshifted QR with numpy):", eigs) # Print eigenvalues for numpy
print("Iterations (numpy):", iter_count) # Print number of iterations numpy


Eigenvalues (unshifted QR with Givens): [5.41421356 4.         2.58578644]
Iterations (Givens): 94
Eigenvalues (unshifted QR with Householder): [5.41421356 4.         2.58578644]
Iterations (Householder): 94
Eigenvalues (unshifted QR with numpy): [5.41421356 4.         2.58578644]
Iterations (numpy): 94


**TASK 4:**
Obtained eigenvalues are almost identical within the 3 methods suggesting a good implementation and results, again showing that the methods are equivalent. Fo further convergence and accuracy checking I have also printed the number of iterations (94 for the 3 methods). I did not expect these many iterations but good to have almost exact results among the 3 methods. Even in most cases they are the same as one can see from random matrix runs (where iteration count changes form small to very big):

In [18]:
A_random = np.random.rand(5, 5)
A_random = (A_random + A_random.T) / 2  # Symmetrize

# Givens
eigs, A_final, iter_count, off_hist = unshifted_qr_eig(A_random, method='givens')  # Givens
print("Eigenvalues (unshifted QR with Givens) for random matrix:", eigs)  # Print eigenvalues for Givens
print("Iterations (Givens):", iter_count)  # Print number of iterations for Givens

# Householder
eigs, A_final, iter_count, off_hist = unshifted_qr_eig(A_random, method='householder')  # Householder
print("Eigenvalues (unshifted QR with Householder) for random matrix:", eigs)  # Print eigenvalues for Householder
print("Iterations (Householder):", iter_count)  # Print number of iterations for Householder

# numpy
eigs, A_final, iter_count, off_hist = unshifted_qr_eig(A_random, method='numpy')  # Numpy
print("Eigenvalues (unshifted QR with numpy) for random matrix:", eigs)  # Print eigenvalues for numpy
print("Iterations (numpy):", iter_count)  # Print number of iterations for numpy

Eigenvalues (unshifted QR with Givens) for random matrix: [ 2.50849166  0.66864594 -0.41153689  0.30520262 -0.28553389]
Iterations (Givens): 410
Eigenvalues (unshifted QR with Householder) for random matrix: [ 2.50849166  0.66864594 -0.41153689  0.30520262 -0.28553389]
Iterations (Householder): 410
Eigenvalues (unshifted QR with numpy) for random matrix: [ 2.50849166  0.66864594 -0.41153689  0.30520262 -0.28553389]
Iterations (numpy): 410


In [21]:
A_random = np.random.rand(5, 5)
A_random = (A_random + A_random.T) / 2  # Symmetrize

# Givens
eigs, A_final, iter_count, off_hist = unshifted_qr_eig(A_random, method='givens')  # Givens
print("Eigenvalues (unshifted QR with Givens) for random matrix:", eigs)  # Print eigenvalues for Givens
print("Iterations (Givens):", iter_count)  # Print number of iterations for Givens

# Householder
eigs, A_final, iter_count, off_hist = unshifted_qr_eig(A_random, method='householder')  # Householder
print("Eigenvalues (unshifted QR with Householder) for random matrix:", eigs)  # Print eigenvalues for Householder
print("Iterations (Householder):", iter_count)  # Print number of iterations for Householder

# numpy
eigs, A_final, iter_count, off_hist = unshifted_qr_eig(A_random, method='numpy')  # Numpy
print("Eigenvalues (unshifted QR with numpy) for random matrix:", eigs)  # Print eigenvalues for numpy
print("Iterations (numpy):", iter_count)  # Print number of iterations for numpy

Eigenvalues (unshifted QR with Givens) for random matrix: [ 2.91128113 -0.54922574  0.25340445 -0.05082824 -0.00566829]
Iterations (Givens): 41
Eigenvalues (unshifted QR with Householder) for random matrix: [ 2.91128113 -0.54922574  0.25340445 -0.05082824 -0.00566829]
Iterations (Householder): 41
Eigenvalues (unshifted QR with numpy) for random matrix: [ 2.91128113 -0.54922574  0.25340445 -0.05082824 -0.00566829]
Iterations (numpy): 41


**TASK 5:**
First discuss execution times, iteration count has been already shown. Then, numerical stability and accuracy. Next we discuss the 3 methods in a summary and finally a conclusion about teh task.

In [26]:
# Measure execution times for comparing efficiency:
import time
sizes = [2, 10, 50, 100, 200, 500, 1000]
times_givens = []
times_householder = []
times_numpy = []

for n in sizes:
    A = np.random.rand(n, n)

    # Givens
    start = time.perf_counter()
    Qg, Rg = qr_givens(A)
    end = time.perf_counter()
    times_givens.append(end - start)

    # Householder
    start = time.perf_counter()
    Qh, Rh = qr_householder(A)
    end = time.perf_counter()
    times_householder.append(end - start)

    # NumPy
    start = time.perf_counter()
    Qn, Rn = np.linalg.qr(A)
    end = time.perf_counter()
    times_numpy.append(end - start)

print(times_givens)
print(times_householder)
print(times_numpy)


[0.0003421620003791759, 0.00019496699951560004, 0.0004288419995646109, 0.004212046000247938, 0.004663800000344054, 0.038334011000188184, 0.1964720510004554]
[5.148000036570011e-05, 8.330000036949059e-05, 0.0005647980005960562, 0.0008844829999361536, 0.0038490710003316053, 0.03290138400006981, 0.17570847099977982]
[7.470199943782063e-05, 7.00290001987014e-05, 0.00024582900005043484, 0.0008302589994855225, 0.003715370999998413, 0.030003531000147632, 0.16678844099988055]


In [28]:
n = 5  # or any size you want to test
A = np.random.rand(n, n)

# Givens
Q_g, R_g = qr_givens(A)
err_fact_g = np.linalg.norm(Q_g @ R_g - A)
err_orth_g = np.linalg.norm(Q_g.T @ Q_g - np.eye(n))
print("Givens:")
print("Reconstruction error:", err_fact_g)
print("Orthogonality error:", err_orth_g)
print()

# Householder
Q_h, R_h = qr_householder(A)
err_fact_h = np.linalg.norm(Q_h @ R_h - A)
err_orth_h = np.linalg.norm(Q_h.T @ Q_h - np.eye(n))
print("Householder:")
print("Reconstruction error:", err_fact_h)
print("Orthogonality error:", err_orth_h)
print()

# NumPy
Q_np, R_np = np.linalg.qr(A)
err_fact_np = np.linalg.norm(Q_np @ R_np - A)
err_orth_np = np.linalg.norm(Q_np.T @ Q_np - np.eye(n))
print("numpy's QR:")
print("Reconstruction error:", err_fact_np)
print("Orthogonality error:", err_orth_np)

Givens:
Reconstruction error: 1.091966747121334e-15
Orthogonality error: 1.190255306366136e-15

Householder:
Reconstruction error: 1.091966747121334e-15
Orthogonality error: 1.190255306366136e-15

numpy's QR:
Reconstruction error: 1.091966747121334e-15
Orthogonality error: 1.190255306366136e-15


 From these measures we can see that overall Givens is significantly slower. Then the other 2 methods are pretty similar in terms of running time but as N starts getting bigger the difference becomes more evident (around 10% for large matrix size). So if our goal was to have the fastest performance we should use numpy and discard Givens.

We see that all methods yield errors in the order of exponent 15 or 16 which falls in machine precision so all 3 methods are reproducing the original matrix close to perfection so in terms of accuracy they perform equally well.  

I believe that all these analysis and coding is complete enough so I will not be showing more measures. Conclude form my code and analysis plus reading and "resources" that:

1. Householder is the method of choice for dense factorizations as it zeroes out an entire column in a single transformation; it is overall stable and easy to implement.

2. Givens mehod is the choice when we do not need to zero out as much as in HH but it is enough with small number of elements; need to incrementally update a QR factorization here adding/removing a row/column can be done with feew Givens rotations not needing factorizing from zero. Also considerably stable.

3. Numpy is the most optimal and fast one; also when one doe snot want to code more than small number of lines it is the best. Time put into coding vs result has the best ratio by far.

4. In terms of numerical stability teh results are great as the errors are small, good stability and they match to many decimals the original matrices.

5. All 3 methods return pretty similar results in terms of iteration counts, stability, accuracy, numerical stability...

 **CONCLUSION:**
 I have enjoyed this task very much as it seemed intuitive to follow, exciting to do and some of my hypothesis were accurate and some other were far from reality so had both the confirmation of my undrestanding and the learning from being mistaken. Also I got the chance of coding some parts with Blackbox AI which has been a great tool for fast coding. Plus reviewing notes from ALgebra and Linear Geometry for matrices when needed. I like when multiple areas of knowledge converge as here with Algebra part, AI part, coding(Python) part and of course the course itself: Numerical Methods.

 Task 4 was more of a nightmare for me :). Also the code was significantly slower in comparsion to this one, here we have some runs of hundreds of iterations and they are done in a second or so, no wait at all, the other needed some time

Also I got the chance of switching form Visual Studio Code and Jupyter notebook to Google Collab that I had never used before and that can be easily exported to multiple formats or even link it with Github plus interface of coding/writing text has been nice for me.